[workspace]

resolver = "2"

members = [
    "compiler",
    "lsp-server",
]

default-members = [
    "compiler",
]

# Unfortunately, this doesn't work yet. https://github.com/rust-lang/cargo/issues/7290#issuecomment-1030158987
# default-run = "ntlcc"
